In [1]:
import numpy as np

In [3]:
a = np.arange(100)

In [8]:
one = np.ones((3,2))

In [14]:
zero = np.zeros((2,3))

In [15]:
one

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
zero.shape

(2, 3)

In [18]:
zero.reshape(3,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [24]:
np.diag([1,2,2.0,4,5,5])

array([[1., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 4., 0., 0.],
       [0., 0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 0., 5.]])

In [25]:
np.full((3,2),2.2)

array([[2.2, 2.2],
       [2.2, 2.2],
       [2.2, 2.2]])

In [27]:
np.full((3,2),2.2,dtype=np.int)

array([[2, 2],
       [2, 2],
       [2, 2]])

In [28]:
v = np.array([1,2,3])

In [29]:
v

array([1, 2, 3])

In [30]:
np.tile(v,(3,2))

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

In [33]:
50*np.random.random() + 2

25.1284920402012

In [35]:
np.random.random([3,3])

array([[0.98347525, 0.62697267, 0.72778643],
       [0.07052273, 0.5531371 , 0.07629146],
       [0.69832621, 0.30295777, 0.10169338]])

In [36]:
c = range(10000)

In [37]:
c

range(0, 10000)

In [38]:
%timeit [i**3 for i in c]

2.37 ms ± 88.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [39]:
c_numpy = np.arange(10000)

In [40]:
c_numpy

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [42]:
c[44]

44

In [43]:
c_numpy[44]

44

In [53]:
print("They are almost the same")

They are almost the same


In [54]:
%timeit c_numpy ** 5

23.3 µs ± 136 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [55]:
%timeit [i ** 5 for i in c]

2.51 ms ± 17 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [70]:
line = np.linspace(1,50,3)

In [71]:
line

array([ 1. , 25.5, 50. ])

In [73]:
line.size

3

In [88]:
test_reshape = np.arange(18)

In [89]:
test_reshape.shape

(18,)

In [91]:
two_dimen = test_reshape.reshape(9,2)

In [92]:
two_dimen.shape

(9, 2)

In [94]:
three_dimen_one = test_reshape.reshape(3,2,3)

In [98]:
three_dimen_one  #2,3 and 2,3 and 2,3

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [96]:
three_dimen_two = test_reshape.reshape(2,3,3)

In [99]:
three_dimen_two #3,3 and 3,3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [107]:
three_dimen_three = test_reshape.reshape(3,3,2)

In [109]:
three_dimen_three  # 3 pages , 3 rows , 2 columns

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

In [117]:
three_dimen_three = test_reshape.reshape(1,6,3)

In [116]:
three_dimen_three

(1, 6, 3)

In [118]:
three_dimen_three.shape

(1, 6, 3)

In [142]:
np.arange(100).reshape(5,4,-1)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [143]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [144]:
a = [2,4,6,8,10,12,14,16]

In [148]:
a = np.array([2,4,6,10,12,14,16])

In [149]:
a[0]

2

In [150]:
a

array([ 2,  4,  6, 10, 12, 14, 16])

In [153]:
a[[2,4]]

array([ 6, 12])

In [154]:
a[2:]

array([ 6, 10, 12, 14, 16])

In [158]:
a[2:5]

array([ 6, 10, 12])

In [159]:
a[2:2]

array([], dtype=int64)

In [162]:
a[2:47293723947239:2]

array([ 6, 12, 16])

In [163]:
a[2::2]

array([ 6, 12, 16])

In [165]:
a_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [166]:
a_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [167]:
a

array([ 2,  4,  6, 10, 12, 14, 16])

In [169]:
a_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
a_arr[2,3]

IndexError: index 3 is out of bounds for axis 1 with size 3

In [173]:
a_arr[2,1]

8

In [175]:
n_test = np.arange(0,10,2)

In [176]:
n_test

array([0, 2, 4, 6, 8])

In [177]:
two_dimen

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [178]:
emp = np.empty([3,2])

In [179]:
emp

array([[0.00000000e+000, 4.94065646e-324],
       [3.95252517e-323, 4.93621120e-312],
       [4.93769266e-312, 4.93917441e-312]])

In [207]:
emp > 0

array([[False,  True],
       [ True,  True],
       [ True,  True]])

In [183]:
zero.shape

(2, 3)

In [189]:
three = np.ones((2,3,5))

In [190]:
three

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [199]:
test = np.array([2,3])

In [200]:
test

array([2, 3])

In [201]:
np.array((2,3))

array([2, 3])

In [208]:
a_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [216]:
a_arr[(a_arr>2) & (a_arr<5) & (a_arr != 3)]

array([4])

In [224]:
a = np.array([2,4,6,10,12,14,16])

In [225]:
a

array([ 2,  4,  6, 10, 12, 14, 16])

In [226]:
b = a

In [227]:
b

array([ 2,  4,  6, 10, 12, 14, 16])

In [228]:
b[0]= 15

In [229]:
b

array([15,  4,  6, 10, 12, 14, 16])

In [230]:
a

array([15,  4,  6, 10, 12, 14, 16])

In [231]:
np.shares_memory(a,b)

True

In [232]:
a_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [241]:
transform_arr = np.array([[1,2,3],[4,5,6]])

In [242]:
transform_arr

array([[1, 2, 3],
       [4, 5, 6]])

In [243]:
transform_arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [244]:
transform_arr == transform_arr.T

/home/minlaxz/anaconda3/envs/laxz/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [245]:
a

array([15,  4,  6, 10, 12, 14, 16])

In [247]:
a = np.array([[1,2,3],[4,5,6]])

In [248]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [249]:
b = np.array([[7,8,9],[10,11,12]])

In [250]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [251]:
a == b

array([[False, False, False],
       [False, False, False]])

In [252]:
a - b

array([[-6, -6, -6],
       [-6, -6, -6]])

In [254]:
np.vstack((a,b))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [256]:
np.hstack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [261]:
a = np.arange(1,10)

In [262]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [268]:
np.sin(b)

array([[ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292]])

In [265]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [269]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [270]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [273]:
np.sum(a), np.sum(b) , np.sum(c)

(45, 57, 49995000)

In [282]:
np.median(b)

9.5

In [283]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [284]:
np.sum(b)

57

In [285]:
a.std()

2.581988897471611

In [286]:
b.std()

1.707825127659933

In [287]:
z = np.array([2,3,4,5])

In [288]:
z.sum()

14

In [289]:
z.mean()

3.5

In [290]:
z.std()

1.118033988749895

In [294]:
np.sqrt(1.25)

1.118033988749895

In [295]:
np.sqrt(0.25)

0.5

In [296]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [297]:
a.shape

(9,)

In [300]:
a_re = a.reshape(3,3)

In [301]:
np.linalg.det(a_re)

-9.51619735392994e-16